kind: pipeline
type: docker
name: ARM build and release (install)

platform:
  os: linux
  arch: arm64

steps:
  - name: build
    image: ubuntu:20.04
    environment:
      DEBIAN_FRONTEND: noninteractive
      TZ: America/Los_Angeles
    commands:
    - apt update && apt install -y build-essential cmake libcurl4-gnutls-dev git
    - cmake -E make_directory build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DMSYNC_USER_CONFIG=ON -DMSYNC_FILE_LOG=OFF
    - cmake --build . --config Release --parallel
    - strip --strip-unneeded msync
    - ./msync
    - ./msync version
    - ./msync yeehaw
    - ctest -C Release --output-on-failure --schedule-random -j 8
    - mkdir ../dist
    - mv msync ../dist/msync-${DRONE_TAG}-install-linux-arm64-gcc
    - ls ../dist

  - name: wait to publish
    image: ubuntu:20.04
    commands:
    - sleep 10m
    when:
      event: tag

  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files:
        - dist/*
    when:
      event: tag
---
kind: pipeline
type: docker
name: ARM build and release (portable)

platform:
  os: linux
  arch: arm64

steps:
  - name: build
    image: ubuntu:20.04
    environment:
      DEBIAN_FRONTEND: noninteractive
      TZ: America/Los_Angeles
    commands:
    - apt update && apt install -y build-essential cmake libcurl4-gnutls-dev git
    - cmake -E make_directory build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release 
    - cmake --build . --config Release --parallel
    - strip --strip-unneeded msync
    - ./msync
    - ./msync version
    - ./msync yeehaw
    - ctest -C Release --output-on-failure --schedule-random -j 8
    - mkdir ../dist
    - mv msync ../dist/msync-${DRONE_TAG}-portable-linux-arm64-gcc
    - ls ../dist

  - name: wait to publish
    image: ubuntu:20.04
    commands:
    - sleep 10m
    when:
      event: tag

  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files:
        - dist/*
    when:
      event: tag
