if((CMAKE_BUILD_TYPE MATCHES Release) OR (CMAKE_BUILD_TYPE MATCHES MinSizeRel))
	message("Testing for IPO support...")
	include(CheckIPOSupported)
	check_ipo_supported(RESULT ipo_is_supported OUTPUT error)
	if (ipo_is_supported)
		cmake_policy(SET CMP0069 NEW) #don't complain about cpr having lower cmake requirements
		message(STATUS "IPO / LTO enabled!")
		set_property(TARGET msync common parse sync ${CPR_LIBRARIES} PROPERTY INTERPROCEDURAL_OPTIMIZATION TRUE)
	else()
		message(STATUS "IPO / LTO not supported: <${error}>")
	endif()
endif()
